ALTER TABLE Users
ADD CONSTRAINT DF_Users_Id DEFAULT NEWID() FOR Id

ALTER TABLE Roles
ADD CONSTRAINT DF_Roles_Id DEFAULT NEWID() FOR Id

ALTER TABLE Beneficiaries
ADD CONSTRAINT DF_Beneficiaries_Id DEFAULT NEWID() FOR Id

ALTER TABLE Payments
ADD CONSTRAINT DF_Payments_Id DEFAULT NEWID() FOR Id

ALTER TABLE Employees
ADD CONSTRAINT DF_Employees_Id DEFAULT NEWID() FOR Id

ALTER TABLE SalaryDisbursements
ADD CONSTRAINT DF_SalaryDisbursements_Id DEFAULT NEWID() FOR Id

ALTER TABLE Documents
ADD CONSTRAINT DF_Documents_Id DEFAULT NEWID() FOR Id

ALTER TABLE Reports
ADD CONSTRAINT DF_Reports_Id DEFAULT NEWID() FOR Id

